services:
  postgres:
    image: postgres:15
    container_name: hw02_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hw02"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: hw02_app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: